# Generated by Django 2.2.2 on 2020-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=100, verbose_name='店名')),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリ')),
                ('text', models.TextField(verbose_name='説明')),
                ('hours', models.TextField(verbose_name='営業時間')),
                ('closed', models.CharField(max_length=50, verbose_name='定休日')),
                ('address', models.TextField(verbose_name='住所')),
                ('phone', models.CharField(max_length=14, verbose_name='電話番号')),
            ],
        ),
    ]
